import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '../components/Button'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import {motion,AnimatePresence} from "framer-motion";
const Home: NextPage = () => {
  return (
    <div className='h-screen scrollbar'

    >
      <Head>
        <title>Alokas Registration Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* header  */}
<Header />
   <motion.main     initial={{y:"100vh"}}
    animate={{y:0}}
    exit={{y:"-100vh"}}
    transition={{ease:"easeInOut"}}>
    <h1 className='text-center items-center font-extrabold mt-[20%] text-3xl'> ALoKAS Tuition Registration Form</h1>
    {/* banner */}
    <section>
      
      <div
      className='flex justify-center text-center items-center mt-[5%] '>
        
        <Link href="/page1" passHref>
      <a><Button value = {"Start"} /></a>
      </Link>
      </div>
      {/* row */}
            {/* row */}
      {/* row */}
      {/* row */}
      {/* row */}
      {/* row */}

    </section>
   </motion.main>
    </div>
  )
}

export default Home
